name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
description: ${project.description}
author: NerdsWBNerds
url: ${project.url}
api-version: 1.13
commands:
   warp:
      description: 显示传送点列表，传送到指定传送点，或将其他玩家传送到指定传送点。
      usage: /<command> <传送点> || /<command> <玩家> <传送点>
      aliases: [ezwarp]
   listwarps:
      description: 显示所有可用的传送点列表。
      usage: /<command> <页码>
      aliases: [ezwarplist, listwarp, ezlistwarp, warplist, ezlistwarps, warps, ezwarps]
   setwarp:
      description: 在你的当前位置设置一个传送点。
      usage: /<command> <传送点名称>
      aliases: [ezaddwarp, ezsetwarp, addwarp]
   delwarp:
      description: 删除指定名称的传送点。
      usage: /<command> <传送点名称>
      aliases: [ezdeletewarp, ezremovewarp, ezdelwarp, deletewarp, removewarp]
   easywarp:
      description: EasyWarp 插件通用命令。
      usage: /<command> <help | reload>
      aliases: [ew, ez, ezw]